<?php
// $Id: admin_changepassword.module
/**
* @uthor VIsions Team
* 22/04/2015 */


function drupal_custom_permission(){
	return array('Drupal Hook'  => array('title' => t('Drupal Hook')));
}

function drupal_custom_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'comment_node_news_form'){
		unset($form['_author']);
	}
	if($form_id == "user_register_form"){
               
		unset($form['account']['name']);
		unset($form['account']['name']['#description']);
		unset($form['account']['pass']['#description']);
		unset($form['account']['mail']['#description']);
		$form['account']['mail']['#title'] = t('E-mail');
        $form['account']['mail']['#rules'] = array(array('rule' => 'email', 'error' => 'Please enter the valid E-mail.'));
        $form['account']['pass']['#type'] = 'password';
		$form['account']['pass']['#title'] = 'Password';
		$form['account']['pass']['#title'] = 'Password';
		//$form['#submit'][] = 'drupal_custom_check';			
	}
	if($form_id == "user_login")
	{
		 //array_unshift($form['#validate'][] = 'login_form_validate');
		unset($form['name']['#description']);
		unset($form['pass']['#description']);
	}
	
	switch ($form_id) 
	{
		case 'user_register_form':
			$form['#submit'][] = 'drupal_custom_user_register_submit';
			$form['#validate'][] = 'drupal_custom_register_validate';
		break;
    }
	if($form_id == "comment_node_news_form"){
		unset($form['_author']);		
	}
}
function drupal_custom_register_validate($form, &$form_state){
	//echo '<pre>'; print_r($form); die();
	$email = $form['account']['mail']['#value'];
	 if(db_query("SELECT COUNT(*) FROM {users} WHERE mail = :mail;", array(':mail' =>  $email))->fetchField())
	{
		form_set_error('email', t('E-mail address is already exist!'));
        drupal_goto(current_path(),array('query'=>array('registerfailed'=>'y')));
	}
}
function drupal_custom_user_register_submit($form, &$form_state) {
 
	global $base_url; 
	global $user;
	$data = array();
	$name = $user->field_name['und'][0]['value'];
	$uid = $user->uid;
	$username = $user->name;
	$data['name'] = $name;
	$data['uid'] = $uid;
	$data['username'] = $username;
	$id = insertUserProfileData($data);
	$redirectUrl = $base_url.'/?getstarted=yes';
	$form_state['redirect'] = $redirectUrl;
}

function drupal_custom_profile_data($uid){
	$res = db_select('chuang_user', 's')
			->fields('s')
			->condition('drupal_user_id', $uid)
			->execute()
			->fetch();
	return $res;
}
function drupal_custom_startup_data($uid){
	$res = db_select('chuang_startup', 's')
			->fields('s')
			->condition('created_by', $uid)
			->execute()
			->fetch();
	return $res;
}
function drupal_custom_company_users($sid){
	$res = db_select('chuang_user_startup', 's')
			->fields('s')
			->condition('startup_id', $sid)
			->execute()
			->fetchAll();
	return $res;
}
function drupal_custom_startup_alldata($uid){
	$res = db_select('chuang_user_startup', 's')
			->fields('s')
			->condition('user_id', $uid)
			->execute()
			->fetchAll();

	return $res;
}
function drupal_custom_startup_singledata($sid){
	$res = db_select('chuang_startup', 's')
			->fields('s')
			->condition('Id', $sid)
			->execute()
			->fetch();
	return $res;
}







